#!/usr/bin/python

import os
import configparser
import tweepy
import glob
import random


def twitt_it(folder, api):
    """Twitts random image from folder"""
    images = glob.glob(folder + "*")
    image_open = images[random.randint(0, len(images))-1]
    api.update_with_media(image_open)


def run():
    """Sets directory so we can read settings.txt.
       See if chance is met
       Authenticate to twitter
       Pass relevant arguments to twitt_it
       """
    # see where is the script is located...
    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    # read configs from file
    config = configparser.ConfigParser()
    config.read(dname + '/bot_settings.txt')
    app_config = config['App']
    folder = app_config['image_folder']
    chance = int(app_config['execution_chance'])
    if random.randint(0, 99) < chance:
        # only if chance is met
        twitter_config = config['Twitter']
        api_key = twitter_config['api_key']
        secret_key = twitter_config['secret_key']
        token = twitter_config['token']
        secret_token = twitter_config['secret_token']

        auth = tweepy.OAuthHandler(api_key, secret_key)
        auth.set_access_token(token, secret_token)
        api = tweepy.API(auth)
        twitt_it(folder, api)

if __name__ == '__main__':
    run()
